[build]
  command = "npm install react-qr-reader@3.0.0-beta-1 && npm install @yudiel/react-qr-scanner &&  npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"   # prints npm version for quick debug
